### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by feelbergood** [feelbergood/CSC522_Project#14]
- [x] Hyper-paramter tuning(grid search for all possible classifiers)
- [x] Other ways of dealing with missing data
- [x] New models: neural network classifiers
- [x] Apply PCA
- [x] Add more data analysis for each dataset
- [x] More metrics for evaluation: ROC, AUC

**Comment by feelbergood** [comment]
Missing data:

- [x] Remove all columns with missing value

- [x] Remove all rows with missing value

- [x] Replace with mean/median/mode value
